replicaCount: 1

image:
  repository: mylo964/myloaxpo-storage-api
  tag: latest
  pullPolicy: Always
 
service:
  type: ClusterIP
  port: "5000"

prometheus:
  server:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "storage_api"
          scrape_interval: 10s
          static_configs:
            - targets: 
                  - "storage-api:5000"
  # Only keep prometheus server for this demo
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  
grafana:
  adminUser: admin
  adminPassword: admin
  datasources: 
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
        - name: Prometheus
          orgId: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://storage-api-prometheus-server:80
          password:
          user:
          database:
          basicAuth: true
          basicAuthUser: admin
          basicAuthPassword: foobar
          withCredentials:
          isDefault: true
          jsonData:
            graphiteVersion: "1.1"
            tlsAuth: false
            tlsAuthWithCACert: false
          secureJsonData:
            tlsCACert:
            tlsClientCert:
            tlsClientKey:
          version: 1
          editable: true